### ISSUE TITLE
Bright-Eyes crashes if a enemy mage moves

### ISSUE THREAD

**Issue by Obi-Wahn** [Henne/Bright-Eyes#12]
Bright-Eyes crashes if a enemy mage moves

Bug Report 1: http://www.crystals-dsa-foren.de/showthread.php?tid=700&pid=114374#pid114374
Bug Report 2:  http://www.crystals-dsa-foren.de/showthread.php?tid=700&pid=114487#pid114487

**Comment by hjr448** [comment]
Hab's mal getestet: Keine Abstürze, allerdings in ca. 15 Versuchen hatte ich einmal einen Grafikfehler. Im rechten 9-er-Feld der Handlungsoptionen war nur noch eine Option da.  Einmal anklicken und zurück. Danach war alles wieder in Ordnung.
