### ISSUE TITLE
Bright Eyes character generation stores CHR files in wrong directory

### ISSUE THREAD

**Issue by Gaddezwerch** [Henne/Bright-Eyes#13]
all new generated chars are not saved in the "DSA1 folder" but in the folder where the DOSBox.exe file is located.
In the game the new generated chars cannot be imported into the game.

Also the created CHR file has a different file size: 1757 bytes compared to 1754 bytes.

Tested under Windows 7 64bit.

**Comment by hjr448** [comment]
the "wrong size" of the file cam probably be solved with "issue #16"
