### ISSUE TITLE
Bright Eyes: SDL.dll wrong?

### ISSUE THREAD

**Issue by Gaddezwerch** [Henne/Bright-Eyes#15]
The SDL.dll in the archive is different from the SDL.dll from the Heldenedition (297 KB compared to the original 438 KB).

As a consequence there seems to be an issue with number pad inputs: All number inputs are not shown correctly and not interpreted correctly, see screenshot where I actually typed in "10" but nothing is shown - even no underscores.

![zahlweg](https://f.cloud.github.com/assets/3389153/99624/2210a1ca-679d-11e2-9183-c392e34947fb.JPG)

Tested under Windows 7 64bit.

**Comment by Henne** [comment]
This is changed by Obi-Wahn (our Windows Releaser)
see: http://www.crystals-dsa-foren.de/showthread.php?tid=3911
